// config.ts - static data that doesnt change during runtime
// filesystem, command lists, ascii art, etc

import type { FileSystemNode } from "./types";

// fake filesystem for terminal
export const fileSystem: { root: FileSystemNode } = {
  root: {
    home: {
      guest: {
        vault: {},
        projects: {
          "pietrouni.com": "FILE",
          "terraform-modules": "FILE",
          "network-automation": "FILE",
        },
        photos: {
          "vacation.jpg": "FILE",
          "setup.png": "FILE",
        },
        experiments: {
          "prototype-1.html": "FILE",
          "test-render.html": "FILE",
        },
        "readme.md": "FILE",
        "todo.txt": "FILE",
        ".config": "FILE",
        ".secrets": "FILE",
      },
    },
    bin: {},
    etc: {},
  },
};

// ascii art alphabet for the ascii command
export const asciiAlpha: Record<string, string[]> = {
  A: ["  A  ", " A A ", "AAAAA", "A   A", "A   A"],
  B: ["BBBB ", "B   B", "BBBB ", "B   B", "BBBB "],
  C: [" CCC ", "C    ", "C    ", "C    ", " CCC "],
  D: ["DDDD ", "D   D", "D   D", "D   D", "DDDD "],
  E: ["EEEEE", "E    ", "EEEEE", "E    ", "EEEEE"],
  F: ["FFFFF", "F    ", "FFFF ", "F    ", "F    "],
  G: [" GGG ", "G    ", "G  GG", "G   G", " GGG "],
  H: ["H   H", "H   H", "HHHHH", "H   H", "H   H"],
  I: [" III ", "  I  ", "  I  ", "  I  ", " III "],
  J: ["JJJJJ", "  J  ", "  J  ", "J J  ", " J   "],
  K: ["K   K", "K  K ", "KKK  ", "K  K ", "K   K"],
  L: ["L    ", "L    ", "L    ", "L    ", "LLLLL"],
  M: ["M   M", "MM MM", "M M M", "M   M", "M   M"],
  N: ["N   N", "NN  N", "N N N", "N  NN", "N   N"],
  O: [" OOO ", "O   O", "O   O", "O   O", " OOO "],
  P: ["PPPP ", "P   P", "PPPP ", "P    ", "P    "],
  Q: [" QQQ ", "Q   Q", "Q   Q", "Q  Q ", " QQ Q"],
  R: ["RRRR ", "R   R", "RRRR ", "R  R ", "R   R"],
  S: [" SSS ", "S    ", " SSS ", "    S", "SSSS "],
  T: ["TTTTT", "  T  ", "  T  ", "  T  ", "  T  "],
  U: ["U   U", "U   U", "U   U", "U   U", " UUU "],
  V: ["V   V", "V   V", "V   V", " V V ", "  V  "],
  W: ["W   W", "W   W", "W W W", "WW WW", "W   W"],
  X: ["X   X", " X X ", "  X  ", " X X ", "X   X"],
  Y: ["Y   Y", " Y Y ", "  Y  ", "  Y  ", "  Y  "],
  Z: ["ZZZZZ", "   Z ", "  Z  ", " Z   ", "ZZZZZ"],
  0: [" 000 ", "0  00", "0 0 0", "00  0", " 000 "],
  1: ["  1  ", " 11  ", "  1  ", "  1  ", "11111"],
  2: [" 222 ", "2   2", "   2 ", "  2  ", "22222"],
  3: ["33333", "    3", "  33 ", "    3", "33333"],
  4: ["   4 ", "  44 ", " 4 4 ", "44444", "   4 "],
  5: ["55555", "5    ", "5555 ", "    5", "5555 "],
  6: [" 666 ", "6    ", "6666 ", "6   6", " 666 "],
  7: ["77777", "    7", "   7 ", "  7  ", " 7   "],
  8: [" 888 ", "8   8", " 888 ", "8   8", " 888 "],
  9: [" 999 ", "9   9", " 9999", "    9", " 999 "],
  " ": ["     ", "     ", "     ", "     ", "     "],
};

// command lists for tab autocomplete
export const PIETROS_COMMANDS: string[] = [
  "help",
  "clear",
  "whoami",
  "pwd",
  "ls",
  "ll",
  "cd",
  "mkdir",
  "touch",
  "rmdir",
  "cat",
  "open",
  "calc",
  "guess",
  "traceroute",
  "tracert",
  "dig",
  "curl",
  "docker",
  "terraform",
  "cisco",
  "ssh",
  "version",
  "uptime",
  "clock",
  "quote",
  "neofetch",
  "ascii",
  "cowsay",
  "figlet",
  "flip",
  "rps",
  "8ball",
  "sudo",
  "rm",
  "exit",
  "pietro",
  "matrix",
  "hack",
  "about",
  "contact",
  "projects",
  "resume",
  "hlx",
  "fallout",
  "cyberpunk",
  "rain",
  "sl",
  "noclip",
  "man",
  "history",
  "skills",
  "timeline",
];

export const CYBERPUNK_COMMANDS: string[] = [
  "help",
  "scan",
  "breach",
  "daemons",
  "disconnect",
  "exit",
];

export const FALLOUT_COMMANDS: string[] = [
  "help",
  "stats",
  "inv",
  "radio",
  "exit",
  "disconnect",
];
